return {
  areaBridge = {},
  featureS11N = {
    [1366] = {
      ["__modelID"] = 392,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 2385.71533,
        y = 6.83734131,
        z = 6273.71973,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [8206] = {
      ["__modelID"] = 252,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 3426.12036,
        y = 6.83734131,
        z = 1165.52087,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [9533] = {
      ["__modelID"] = 397,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 2924.12695,
        y = 6.83734131,
        z = 3749.29614,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [9860] = {
      ["__modelID"] = 405,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 6624.6958,
        y = 6.83734131,
        z = 3740.19409,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [10025] = {
      ["__modelID"] = 256,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 5743.92773,
        y = 6.83734131,
        z = 2025.83447,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [13350] = {
      ["__modelID"] = 388,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 752.607727,
        y = 6.83734131,
        z = 6589.72363,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [16540] = {
      ["__modelID"] = 398,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 633.242798,
        y = 6.83734131,
        z = 280.962158,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [18260] = {
      ["__modelID"] = 396,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 5289.26123,
        y = 6.83734131,
        z = 4498.5166,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [19858] = {
      ["__modelID"] = 390,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 329.665497,
        y = 6.83734131,
        z = 4982.00684,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [20997] = {
      ["__modelID"] = 294,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 320.757874,
        y = 6.83734131,
        z = 4981.35352,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [23005] = {
      ["__modelID"] = 395,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 7490.69043,
        y = 6.83734131,
        z = 7984.26025,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [23020] = {
      ["__modelID"] = 298,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 4743.54785,
        y = 6.83734131,
        z = 7086.25342,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [23889] = {
      ["__modelID"] = 400,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 5750.41309,
        y = 6.83734131,
        z = 2023.92383,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [31658] = {
      ["__modelID"] = 312,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 1598.43823,
        y = 6.83734131,
        z = 4537.65283,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [32137] = {
      ["__modelID"] = 393,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 2472.6731,
        y = 6.83734131,
        z = 8066.9707,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [32162] = {
      ["__modelID"] = 403,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 7652.05713,
        y = 6.83734131,
        z = 1734.46643,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [35102] = {
      ["__modelID"] = 391,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 1608.54382,
        y = 6.83734131,
        z = 4536.79883,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [36292] = {
      ["__modelID"] = 389,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 590.922546,
        y = 6.83734131,
        z = 7423.10986,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [37670] = {
      ["__modelID"] = 330,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 7851.49365,
        y = 6.83734131,
        z = 3179.30737,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [38218] = {
      ["__modelID"] = 332,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 2916.11377,
        y = 6.83734131,
        z = 3749.91528,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [39740] = {
      ["__modelID"] = 402,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 7489.06055,
        y = 6.83734131,
        z = 823.750183,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [40458] = {
      ["__modelID"] = 335,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 7481.21777,
        y = 6.83734131,
        z = 7986.69385,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [41123] = {
      ["__modelID"] = 336,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 580.716431,
        y = 6.83734131,
        z = 7421.47217,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [43713] = {
      ["__modelID"] = 340,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 7474.78662,
        y = 6.83734131,
        z = 826.949341,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [44596] = {
      ["__modelID"] = 394,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 4754.90918,
        y = 6.83734131,
        z = 7086.71045,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [45808] = {
      ["__modelID"] = 399,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 3434.01025,
        y = 6.83734131,
        z = 1167.41162,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [47682] = {
      ["__modelID"] = 346,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 7642.97705,
        y = 6.83734131,
        z = 1736.4519,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [48037] = {
      ["__modelID"] = 401,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 5628.38086,
        y = 6.83734131,
        z = 126.939667,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [48956] = {
      ["__modelID"] = 404,
      defName = "geocrack",
      health = 10000,
      mass = 1000.40002,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = false,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 7863.29297,
        y = 6.83734131,
        z = 3176.90771,
      },
      radiusHeight = {
        height = 0,
        radius = 0,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [49629] = {
      ["__modelID"] = 351,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 746.241089,
        y = 6.83734131,
        z = 6589.20166,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [52744] = {
      ["__modelID"] = 357,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 6612.55176,
        y = 6.83734131,
        z = 3740.66699,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [54313] = {
      ["__modelID"] = 362,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 5621.81348,
        y = 6.83734131,
        z = 122.122803,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [55929] = {
      ["__modelID"] = 364,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 627.764404,
        y = 6.83734131,
        z = 279.880493,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [59279] = {
      ["__modelID"] = 374,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 2370.05859,
        y = 6.83734131,
        z = 6278.33496,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [61892] = {
      ["__modelID"] = 377,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 2463.48975,
        y = 6.83734131,
        z = 8066.771,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
    [63931] = {
      ["__modelID"] = 386,
      defName = "geovent",
      health = 0,
      mass = 100000,
      team = 2,
      blocking = {
        blockEnemyPushing = true,
        blockHeightChanges = false,
        crushable = true,
        isBlocking = false,
        isProjectileCollidable = true,
        isRaySegmentCollidable = true,
        isSolidObjectCollidable = false,
      },
      collision = {
        axis = 2,
        disabled = true,
        offsetX = 0,
        offsetY = 0,
        offsetZ = 0,
        scaleX = 1,
        scaleY = 1,
        scaleZ = 1,
        testType = 1,
        vType = 3,
      },
      midAimPos = {
        aim = {
          x = 0,
          y = 0,
          z = 0,
        },
        mid = {
          x = 0,
          y = 0,
          z = 0,
        },
      },
      pos = {
        x = 5280.27393,
        y = 6.83734131,
        z = 4500.3623,
      },
      radiusHeight = {
        height = 1,
        radius = 1,
      },
      rot = {
        x = 0,
        y = 0,
        z = 0,
      },
      rules = {},
      vel = {
        x = 0,
        y = 0,
        z = 0,
      },
    },
  },
  unitS11N = {},
}
